### ISSUE TITLE
[Workbook] Indicate optional columns in the Excel workbook

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/arpa-reporter#416] opened 2022-07-11 21:30 UTC
At least 2 partners have asked or have been confused by which fields are optional. Can we mark optional columns in the workbook somehow?

**Comment by jcomeau1** [comment] 2022-07-12 12:57
I had proposed months ago to turn to turn the column headers red if they were required, but it didn't seem important at the time.

That said, there are a few drawbacks to that approach anyway, specifically, conditional fields and color blindness. Conditional means they are conditionally required, but that's on a row-by-row basis, not a column basis. The visual cue for conditional fields is to un-gray them, which should hopefully convey the right message to everyone. Turning text (or cells or borders) red means that color blind people will likely not see this (red-green is one of the most common forms of color blindness) as it will likely still look black.

We could just add whether a field is required, optional or conditional to the Help Text. This would be easy and while a user would need to look at (hover over) the help text, at least the information is there. This is my recommendation.

Other ideas welcomed.

**Comment by jcomeau1** [comment] 2022-08-24 22:45
Duplicate of #483, which is already delivered.

**Closed by jcomeau1** 2022-08-24 22:45 UTC
Labels: enhancement
