### ISSUE TITLE
[Partner submission] [Audit Report] Testing this early - Some issues with the mapping beyond my understanding.

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#429] opened 2022-07-13 15:02 UTC
**Submitted Description:**
Hi, 

Medium priority as this is obv the last step in the reporting process, but wanted to test it out early so I can upload the UST portal and see whether it takes. 

1. For FY22Q4, I have the following files for test aggregation (see pic_1).
2. I then click 'Download Treasury Report' and extract the zipped files to my local desktop
3. See attached files for what I get. 

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5335335914521500745/expendituresGT50000BulkUpload.csv
https://www.jotform.com/uploads/grants.dev/212695501572052/5335335914521500745/pic1.PNG
https://www.jotform.com/uploads/grants.dev/212695501572052/5335335914521500745/project18_229233BulkUpload.csv
https://www.jotform.com/uploads/grants.dev/212695501572052/5335335914521500745/project215218BulkUpload.csv
https://www.jotform.com/uploads/grants.dev/212695501572052/5335335914521500745/subawardBulkUpload.csv

**Comment by jcomeau1** [comment] 2022-07-13 15:37
It looks like this is a CR/LF issue. Using the subawardBlukUpload as the example, you can see something happens with Col G where the guidance ends up on A8 and then things continue from there. The root cause for all of these templates is likely the same.

**Comment by trumanc** [comment] 2022-07-13 17:00
I believe this issue was fixed in https://github.com/usdigitalresponse/arpa-reporter/pull/418
We've just deployed that fix to main, so it should be fixed for partners now.

**Comment by trumanc** [comment] 2022-07-14 23:42
Closing this as we believe it is fixed. If you're continuing to see the problem, please re-open!

**Closed by trumanc** 2022-07-14 23:42 UTC
Labels: bug, form submission, Medium Priority
