### ISSUE TITLE
[Partner submission] col L/M (Program Income Earned / Expended) of the EC tabs are not data validated.

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#415] opened 2022-07-11 20:09 UTC
The data validation from Render doesn't work - I can leave it completely blank and Render will not throw an Error.

**Comment by jcomeau1** [comment] 2022-07-11 21:07
Note for all ECs they are columns L/M, except for EC 7, they are columns Q/R. Also note that the output templates (and the input template) have them listed as optional in all cases. Let me see if I can find out what the reality is.

**Comment by jcomeau1** [comment] 2022-07-11 21:20
I sent a note to the partners. It looks like these fields are Optional across the board, so this should be a non-issue. Let's see if there's a scenario we're missing before closing this out.

**Comment by jcomeau1** [comment] 2022-07-12 12:46
Confirmed with partners that these fields are optional.

**Closed by jcomeau1** 2022-07-12 12:46 UTC
Labels: bug, form submission, Medium Priority
